{{- /* render only if secret vars exist */ -}}
{{- if .Values.secretEnv }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "django-sample.fullname" . }}-secret
data:
{{- range $k, $v := .Values.secretEnv }}
  {{ $k }}: {{ $v | b64enc }}
{{- end }}
{{- end }}
