secretEnv:
    DB_USER: ENC[AES256_GCM,data:SAImVJsjIbQ=,iv:Dtj9YyE9ENZvZdlt8nFl7saqomsbClLOvEf5BSNHkDU=,tag:ZXVvkVkH/pGvzV0HW8uLUQ==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:MGOQd2NlzG0=,iv:/SU57eDL+g/5igW6w6GNTY2Cs/geAc3iPJO8ta27QR0=,tag:bIA/fCa+RQlBHVciiMPxkg==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:kh7lUYwdq6X3vzs1dnlqCPc3T9hRqALIyce/ZriIbdF6NODZXjM2Ufbz4AFFGbx+5N6muPRL75t83KOoAf49alczJVTvzWJT5lQ0geoGm9/QxRP5/sajTmwb7QJt2/TLnA==,iv:AjSxRsATzC7uE/PQdNyk1bLAIm4HTXKFi5Gp6Y6GgHk=,tag:YpPn70F53MunwxAQTY6QYQ==,type:str]
sops:
    age:
        - recipient: age1nf5gg4kwqw82dptsa966xppz6pns6ae7casnryksr73ugnvlzg7s6ffhqh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsaU9KbzQrcm9SSHFPSGNY
            UmZmeERwdCs2UUFjVjg4MkYrNHk1ZDZ3Zm5FCjREa1A0L3FyTVVuQlpWMVRNdzRD
            d0w0dTZqbGhUcndHVHQwdXl5WXdGWTgKLS0tIG8yMS9Dbjk5UHZXaTNoZkhhSlFZ
            UzU1Y3J1VVc1OGYvSDhFMVMzRmFxM1EK6F3BGmaP2yUYDAoRuP7jylh7YT5z8/GN
            Bc9mPsLtJsd5BzSv/gZw3Kq00KwDvrYPBX/igSCh00/m5KPc7sdZfA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-07T07:33:40Z"
    mac: ENC[AES256_GCM,data:cw+muG/FpfKJlIUq2wcqemqNTrHdv2FGXw420tgbKeAAs+RBjfuVi2KNm2a9p+Vk9dGHVqu/jWGDh8UxMQJV7o2XJyMKZKgBO3XP3kARtT1qahH+zCuhooAWR4DGcPoFOytxYqeCkaYbWGLNLKB0e5nujZZFpYTKK1Ko7F7Vat4=,iv:kUTWmLhiRJrnu4J++KQSfoEConW8nEg5MGT5hC2K0zU=,tag:+xm2WaxPsDLN5o7ThJ9AQw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
